export const levels = [
  {
    title: 'Acceso restringido',
    kicker: 'NIVEL 1 · TERMINAL DE ARCHIVO',
    prompt: 'Clave de emergencia: instante de interrupción',
    evidence: ['Capturas de las cámaras de seguridad', 'Registro del corte eléctrico'],
    digital: 'La computadora quedó bloqueada después del apagón. Recuperá el acceso para comenzar la investigación.',
    placeholder: '4 caracteres', answer: ['1937'], lock: 'numeric',
    hints: ['Hay más de una referencia temporal entre las evidencias. No todas tienen el mismo grado de confianza.', 'Pensá qué objeto de la sala pudo quedar congelado exactamente cuando se interrumpió la energía.', 'Compará las dos horas y decidí cuál representa el instante real del corte. La terminal espera cuatro caracteres.', 'SOLUCIÓN DIRECTA · El corte ocurrió a las 19:37. Ingresá 1937.'],
    unlock: 'Declaraciones de los cuatro sospechosos',
  },
  {
    title: 'Las coartadas',
    kicker: 'NIVEL 2 · PANEL DE SOSPECHOSOS',
    prompt: 'Ingresá el código de 4 cifras que permite cerrar esta parte de la investigación.',
    evidence: [],
    digital: 'El intervalo crítico va de 19:30 a 19:50. Una marca aislada prueba un momento; para descartar a alguien necesitás cubrir el recorrido completo, sin huecos.',
    placeholder: 'Código de 4 cifras', answer: ['1888'], lock: 'numeric',
    hints: ['Una entrada, una salida o una foto aislada solo prueban un momento.', 'Buscá registros distintos que se completen entre sí, sin dejar huecos en el intervalo.', 'Compará los dos tramos de entrevista de León con su breve paso por la cafetería.', 'SOLUCIÓN DIRECTA · La coartada completa es la de León Costa. Ingresá el código LC-1888 o 1888.'],
    unlock: 'Coartada verificada · nueva pista recuperada',
  },
  {
    title: 'Señales desordenadas',
    kicker: 'NIVEL 3 · RECEPTOR MARÍTIMO',
    prompt: '¿Qué lugar del faro señala el mensaje reconstruido?',
    evidence: [],
    digital: 'Seis registros luminosos recuperados fuera de secuencia.',
    placeholder: '6 caracteres', answer: ['taller', 'el taller', 'taller de restauracion'], lock: 'letters',
    hints: ['Cada patrón de destellos representa una letra. Hay una guía entre tus evidencias que puede ayudarte.', 'Saber las seis letras no alcanza: los registros llegaron desordenados. León dejó reglas sobre la posición de los símbolos.', 'La Brújula abre el mensaje. Las dos Olas deben quedar juntas y el Ancla cierra la señal.', 'El Farol queda antes de las dos Olas y la Llave está inmediatamente antes del Ancla.', 'SOLUCIÓN DIRECTA · Las seis señales forman la palabra TALLER.'],
    unlock: 'Destino de las señales identificado',
  },
  {
    title: 'El corredor oculto',
    kicker: 'NIVEL 4 · SALA DE PLANOS',
    prompt: '¿Qué código de tres cifras revela el recorrido desde INICIO?',
    evidence: ['Sobre de evidencias del nivel 4', 'Material de reconstrucción sin clasificar'],
    digital: 'Al plano público le falta una parte del sector de mantenimiento. Reconstruí sus conexiones antes de examinar el resto de las evidencias.',
    placeholder: '3 cifras', answer: ['937'], lock: 'safe',
    hints: ['Que el fragmento entre por su forma no alcanza. Observá las líneas que llegan a cada borde del hueco.', 'El pasillo, la pared y el conducto deben continuar sin quedar cortados ni atravesarse.', 'Después de reconstruir el plano, compará las marcas y la orientación de los materiales disponibles.', 'El punto de inicio comparte un símbolo con una de las salas del plano.', 'Seguí la trayectoria desde ese símbolo y leé los números de las habitaciones en el orden del recorrido.', 'SOLUCIÓN DIRECTA · El recorrido pasa por 9, 3 y 7. Ingresá 937.'],
    unlock: 'Recorrido del pasadizo confirmado',
  },
  {
    title: 'El registro oculto',
    kicker: 'NIVEL 5 · LABORATORIO',
    prompt: 'Registrá el código recuperado y conectalo con la persona asociada al material.',
    evidence: ['Informe de Conservación', 'Material de lectura del nivel 5'],
    digital: 'Los movimientos del taller registran código, operador, material y destino. Recuperá primero el dato oculto del informe y después buscalo en la tabla.',
    placeholder: 'Conexión', answer: ['banderas', 'sala de banderas', 'la sala de banderas'], lock: 'label',
    hints: ['Hay información que no se distingue a simple vista en el informe.', 'Cuando recuperes un código, buscalo en la primera columna de la tabla de movimientos.', 'En la fila de R-17, relacioná el material Resina RX-4 con la sospechosa que viste trabajar con él.', 'SOLUCIÓN DIRECTA · Registrá R-17, elegí a Martina y confirmá la conexión. El destino es la Sala de Banderas.'],
    unlock: 'Destino de R-17 identificado',
  },
  {
    title: 'La sala de banderas',
    kicker: 'NIVEL 6 · TABLERO DE BANDERAS',
    prompt: '¿Qué palabra forman las cinco banderas?',
    evidence: ['Instrumento de señales impreso'],
    digital: 'Cinco señales numeradas están izadas a distintas alturas. La propia sala conserva una indicación sobre el orden de lectura.',
    placeholder: '5 letras', answer: ['farol', 'el farol'], lock: 'flags',
    hints: ['Usá el instrumento de señales impreso para convertir cada número en una letra.', 'Buscá en la sala una frase relacionada con el recorrido de la luz.', 'Empezá por la bandera más cercana a la fuente de luz y continuá hacia abajo: 1, 22, 13, 10, 7.', 'SOLUCIÓN DIRECTA · Las cinco banderas forman FAROL.'],
    unlock: 'Ubicación indicada por las banderas',
  },
  {
    title: 'El compartimento',
    kicker: 'NIVEL 7 · CERRADURA MECÁNICA',
    prompt: '¿Cuál es el código del compartimento?',
    evidence: ['Sobre dirigido al agente', 'Mecanismo del compartimento preparado'],
    digital: 'Mecanismo del compartimento detectado. La combinación no está registrada en el sistema. Seguí los recorridos IMPARES y PARES para reconstruirla.',
    placeholder: '5 cifras', answer: ['11820'], lock: 'mechanical',
    hints: ['La pieza ya está recortada. Observá qué parte puede moverse y qué marcas permiten alinearla.', 'La alineación revela dos recorridos rotulados IMPARES y PARES. Respetá qué valores quedan señalados en cada uno.', 'El recorrido IMPARES da un resultado de tres cifras y el recorrido PARES uno de dos. Escribilos juntos, en ese orden.', 'SOLUCIÓN DIRECTA · 19 + 21 + 23 + 25 + 30 = 118; 2 + 4 + 6 + 8 + 0 = 20. Ingresá 11820.'],
    unlock: 'Acceso a la acusación final',
  },
];

export const unlockMessages = [
  { audio: '/los-archivos-f/audio/fede-nivel-1.wav', text: 'Confirmado: el corte ocurrió a las 19:37. Siete minutos pueden parecer poco, pero alcanzan para cruzar la sala y utilizar el corredor. Ahora comparemos las declaraciones para saber quién pudo moverse durante ese intervalo.' },
  { audio: '/los-archivos-f/audio/fede-nivel-2.wav', text: 'Coartada verificada. Las fuentes coinciden y cubren todo el intervalo. León queda descartado. Durante la pausa en la cafetería anotó algo extraño en una servilleta. Esa puede ser nuestra siguiente pista.' },
  { audio: '/los-archivos-f/audio/fede-nivel-3.wav', text: '¡TALLER! Las señales no eran un mensaje al azar: estaban marcando el Taller de Mantenimiento. Si alguien conocía ese sistema durante el apagón, pudo haber dejado allí otra parte del recorrido. Vamos a revisar el taller.' },
  { audio: '/los-archivos-f/audio/fede-nivel-4.wav', text: '¡Lo tenemos! La ruta oculta atraviesa 9, 3 y 7. El código abrió el conducto de mantenimiento. Este pasaje lleva hacia una zona que no aparece en el plano público del faro. Sigamos el corredor.' },
  { audio: '/los-archivos-f/audio/fede-nivel-5.wav', text: 'R-17 termina en la Sala de Banderas. El movimiento figura a nombre de T-04 y transporta Resina RX-4, el mismo material que vimos con Martina. Es una conexión importante, pero todavía no alcanza para acusarla.' },
  { audio: '/los-archivos-f/audio/fede-nivel-6.wav', text: 'FAROL no es una contraseña: es una ubicación. Las señales estaban indicando la linterna superior del faro, justo encima de la sala. Allí tiene que estar la última pieza del recorrido.' },
  { audio: '/los-archivos-f/audio/fede-nivel-7.wav', text: 'La combinación encajó y el mecanismo se abrió. Ya reunimos la hora, la ruta, el registro y la ubicación final. Pueden abrir el sobre dirigido al agente: llegó el momento de reconstruir quién actuó, cómo lo hizo y dónde dejó el rubí.' },
];

export const microChecks = [
  [],
  [],
  [],
  [
    { question: '¿Qué fragmento conserva la continuidad del pasillo, la pared y el conducto?', options: ['Fragmento A', 'Fragmento B', 'Fragmento C', 'Fragmento D'], correct: 2, success: 'Reconstrucción compatible.' },
  ],
  [
    { question: '¿Qué sospechosa viste trabajando con Resina RX-4?', options: ['Vera', 'Martina', 'Bruno', 'León'], correct: 1, success: 'La ficha de Martina contiene Resina RX-4. T-04 queda asociado provisionalmente con ella.' },
  ],
  [],
  [],
];
