export const levels = [
  {
    title: 'Acceso restringido',
    kicker: 'NIVEL 1 · TERMINAL DE ARCHIVO',
    prompt: 'Clave de emergencia: instante de interrupción',
    evidence: ['Lote A · Cinco capturas de seguridad (A-01 a A-05)', 'Evidencia B-01 · Registro del corte eléctrico'],
    digital: 'El archivo de las personas presentes quedó bloqueado después del apagón. Recuperá el acceso para continuar la investigación.',
    placeholder: '4 caracteres', answer: ['1937'], lock: 'numeric',
    hints: ['Hay más de una referencia temporal entre las evidencias. No todas tienen el mismo grado de confianza.', 'Pensá qué objeto de la sala pudo quedar congelado exactamente cuando se interrumpió la energía.', 'Compará las dos horas y decidí cuál representa el instante real del corte. La terminal espera cuatro caracteres.'],
    unlock: 'Declaraciones de los cuatro sospechosos',
  },
  {
    title: 'Las coartadas',
    kicker: 'NIVEL 2 · PANEL DE SOSPECHOSOS',
    prompt: 'Ingresá el código de 4 cifras que permite cerrar esta parte de la investigación.',
    evidence: [],
    digital: 'El intervalo crítico va de 19:30 a 19:50. Una marca aislada prueba un momento; para descartar a alguien necesitás cubrir el recorrido completo, sin huecos.',
    placeholder: 'Código de 4 cifras', answer: ['1888'], lock: 'numeric',
    hints: ['Una entrada, una salida o una foto aislada solo prueban un momento.', 'Buscá registros distintos que se completen entre sí, sin dejar huecos en el intervalo.', 'Compará los dos tramos de entrevista de León con su breve paso por la cafetería.'],
    unlock: 'Coartada verificada · nueva pista recuperada',
  },
  {
    title: 'Señales desordenadas',
    kicker: 'NIVEL 3 · RECEPTOR MARÍTIMO',
    prompt: '¿Qué lugar del faro señala el mensaje reconstruido?',
    evidence: [],
    digital: 'Seis registros luminosos recuperados fuera de secuencia.',
    placeholder: '6 caracteres', answer: ['taller', 'el taller', 'taller de restauracion'], lock: 'letters',
    hints: ['Cada patrón de destellos representa una letra. Hay una guía entre tus evidencias que puede ayudarte.', 'Saber las seis letras no alcanza: los registros llegaron desordenados. León dejó reglas sobre la posición de los símbolos.', 'La Brújula abre el mensaje. Las dos Olas deben quedar juntas y el Ancla cierra la señal.', 'El Farol queda antes de las dos Olas y la Llave está inmediatamente antes del Ancla.'],
    unlock: 'Destino de las señales identificado',
  },
  {
    title: 'El corredor oculto',
    kicker: 'NIVEL 4 · CAJA FUERTE',
    prompt: '¿Qué código de tres cifras revela el recorrido desde INICIO?',
    evidence: ['Sobre de evidencias del nivel 4', 'Material de reconstrucción sin clasificar'],
    digital: 'Al plano público le falta una parte del sector de mantenimiento. Reconstruí sus conexiones antes de examinar el resto de las evidencias.',
    placeholder: '3 cifras', answer: ['937'], lock: 'safe',
    hints: ['Que el fragmento entre por su forma no alcanza. Observá las líneas que llegan a cada borde del hueco.', 'El pasillo, la pared y el conducto deben continuar sin quedar cortados ni atravesarse.', 'Después de reconstruir el plano, compará las marcas y la orientación de los materiales disponibles.', 'El punto de inicio comparte un símbolo con una de las salas del plano.', 'Seguí la trayectoria desde ese símbolo y leé los números de las habitaciones en el orden del recorrido.'],
    unlock: 'Recorrido del pasadizo confirmado',
  },
  {
    title: 'El registro oculto',
    kicker: 'NIVEL 5 · LABORATORIO',
    prompt: '¿A qué destino fue enviado el registro R-17?',
    evidence: ['Informe de Conservación', 'Material de lectura del nivel 5'],
    digital: 'Los movimientos del taller registran código, operador, material y destino. Recuperá primero el dato oculto del informe y después buscalo en la tabla.',
    placeholder: 'Destino', answer: ['banderas', 'sala de banderas', 'la sala de banderas'], lock: 'label',
    hints: ['Hay información que no se distingue a simple vista en el informe.', 'Cuando recuperes un código, buscalo en la primera columna de la tabla de movimientos.', 'R-17 fue enviado a la Sala de Banderas. Después observá el material y el operador de esa misma fila.'],
    unlock: 'Destino de R-17 identificado',
  },
  {
    title: 'La sala de banderas',
    kicker: 'NIVEL 6 · TABLERO DE BANDERAS',
    prompt: '¿Qué palabra forman las cinco banderas?',
    evidence: ['G-02 · Guía de banderas del museo'],
    digital: 'Cinco señales están izadas a distintas alturas. Traducirlas no alcanza: la propia sala conserva una indicación sobre el orden de lectura.',
    placeholder: '5 letras', answer: ['farol', 'el farol'], lock: 'flags',
    hints: ['Usá G-02 para traducir las banderas, pero todavía necesitás descubrir el orden.', 'Buscá en la sala una frase relacionada con el recorrido de la luz.', 'Empezá por la bandera más cercana a la fuente de luz y continuá hacia abajo.'],
    unlock: 'Ubicación indicada por las banderas',
  },
  {
    title: 'El compartimento',
    kicker: 'NIVEL 7 · CERRADURA MECÁNICA',
    prompt: '¿Cuál es el código del compartimento?',
    evidence: ['Sobre negro autorizado', 'Plantilla de calibración LF-04, ya preparada'],
    digital: 'Mecanismo LF-04 detectado. La combinación no está registrada en el sistema. La plantilla física contiene el procedimiento de calibración.',
    placeholder: '5 cifras', answer: ['18153'], lock: 'mechanical',
    hints: ['La pieza ya está recortada. Observá qué parte puede moverse y qué marcas permiten alinearla.', 'Cuando esté bien colocada aparecerán seis números y una regla breve que separa dos grupos.', 'Sumá los pares para A, los impares para B y calculá A − B. Escribí A, B y la diferencia en ese orden.'],
    unlock: 'Acceso a la acusación final',
  },
];

export const unlockMessages = [
  { audio: '/los-archivos-f/audio/fede-nivel-1.wav', text: 'Siete minutos pueden parecer poco, pero alcanzan para cruzar la sala y utilizar el corredor. Ahora compará las declaraciones.' },
  { audio: '/los-archivos-f/audio/fede-nivel-2.wav', text: 'Coartada verificada. Las fuentes coinciden y cubren todo el intervalo. León queda descartado. Durante la pausa en la cafetería anotó algo extraño en una servilleta. Esa puede ser nuestra siguiente pista.' },
  { audio: '/los-archivos-f/audio/fede-nivel-3.wav', text: '¡TALLER! Las señales no eran un mensaje al azar: estaban marcando el Taller de Mantenimiento. Si alguien conocía ese sistema durante el apagón, pudo haber dejado allí otra parte del recorrido. Vamos a revisar el taller.' },
  { audio: '/los-archivos-f/audio/fede-nivel-4.wav', text: '¡Lo tenemos! La ruta oculta atraviesa 9, 3 y 7. El código abrió el conducto de mantenimiento. Este pasaje lleva hacia una zona que no aparece en el plano público del faro. Sigamos el corredor.' },
  { audio: '/los-archivos-f/audio/fede-nivel-5.wav', text: 'R-17 termina en la Sala de Banderas. El movimiento figura a nombre de T-04 y transporta Resina RX-4, el mismo material que vimos con Martina. Es una conexión importante, pero todavía no alcanza para acusarla.' },
  { audio: '/los-archivos-f/audio/fede-nivel-6.wav', text: 'FAROL no es una contraseña: es una ubicación. Las señales estaban indicando la linterna superior del faro. Vamos.' },
  { audio: '/los-archivos-f/audio/fede-nivel-7.wav', text: 'El mecanismo se abrió. Ya tenés autorización para abrir el Sobre Negro y continuar con la reconstrucción final.' },
];

export const microChecks = [
  [],
  [],
  [],
  [
    { question: '¿Qué fragmento conserva la continuidad del pasillo, la pared y el conducto?', options: ['Fragmento A', 'Fragmento B', 'Fragmento C', 'Fragmento D'], correct: 2, success: 'Reconstrucción compatible.' },
  ],
  [
    { question: '¿Qué sospechosa viste trabajando con Resina RX-4?', options: ['Vera', 'Martina', 'Bruno', 'León'], correct: 1, success: 'La ficha de Martina contiene Resina RX-4. T-04 queda asociado provisionalmente con ella.' },
  ],
  [],
  [
    { question: '¿Qué confirma que LF-04 quedó correctamente colocada?', options: ['Se ven seis números y una regla completa', 'Todas las líneas desaparecen', 'La plantilla forma un círculo'], correct: 0, success: 'La alineación correcta revela los seis valores y el procedimiento de calibración.' },
  ],
];
