import { useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import { DEFAULT_AURORA_CONFIG, type AuroraConfig, type AuroraLocale, type AuroraPaletteTokens } from '../aurora/config';
import './siena.css';

type Props={locale:AuroraLocale;embedded?:boolean;config?:Partial<AuroraConfig>;paletteTokens:AuroraPaletteTokens;sectionOrder?:string[]};
const A='/siena/images/';
const copy={
 es:{event:'Mis quince',open:'Abrir invitación',scroll:'Deslizá para descubrir',less:'Falta muy poco',count:'Cuenta regresiva',units:['Días','Horas','Minutos','Segundos'],where:'¿Cuándo y dónde?',map:'Cómo llegar',calendar:'Agendar evento',quote:'“Los momentos más felices de la vida se vuelven maravillosos cuando los compartimos con quienes queremos. Vos estás entre ellos, ¡te espero!”',dress:'Código de vestimenta',dressCopy:'Elegante formal',details:'Ver detalles',schedule:'Cronograma',parallax:'¡Te espero para celebrar!',gallery:'Galería de fotos',galleryCopy:'Un recorrido por momentos inolvidables.',gifts:'Mesa de regalos',giftCopy:'Tu presencia es nuestro mejor regalo. Si deseás hacer un presente, podés consultar los datos.',photos:'Compartí tus fotos',photosCopy:'Subí tus fotos del evento a nuestra carpeta compartida.',social:'Instagram y redes',socialCopy:'Etiquetame usando nuestro hashtag:',spotify:'Spotify',spotifyCopy:'¿Qué canción no puede faltar?',pass:'Tu pase',passCopy:'Presentá tu código QR en la entrada del salón.',rsvp:'Confirmación de asistencia',deadline:'Por favor confirmá tu asistencia antes del 1 de noviembre.',confirm:'Confirmar asistencia'},
 en:{event:'My fifteenth',open:'Open invitation',scroll:'Scroll to discover',less:'Almost time',count:'Countdown',units:['Days','Hours','Minutes','Seconds'],where:'When and where?',map:'Directions',calendar:'Save the date',quote:'“The happiest moments become wonderful when shared with those we love. You are one of them — I hope you can join me!”',dress:'Dress code',dressCopy:'Formal attire',details:'View details',schedule:'Schedule',parallax:'I hope you can celebrate with me!',gallery:'Photo gallery',galleryCopy:'A journey through unforgettable moments.',gifts:'Gift table',giftCopy:'Your presence is my greatest gift.',photos:'Share your photos',photosCopy:'Upload your event photos to our shared album.',social:'Instagram',socialCopy:'Tag me using:',spotify:'Spotify',spotifyCopy:'Which song cannot be missing?',pass:'Your pass',passCopy:'Show your QR code at the entrance.',rsvp:'RSVP',deadline:'Please reply before November 1.',confirm:'Confirm attendance'},
 pt:{event:'Meus quinze',open:'Abrir convite',scroll:'Deslize para descobrir',less:'Falta muito pouco',count:'Contagem regressiva',units:['Dias','Horas','Minutos','Segundos'],where:'Quando e onde?',map:'Como chegar',calendar:'Adicionar à agenda',quote:'“Os momentos mais felizes ficam maravilhosos quando compartilhados com quem amamos. Você está entre eles!”',dress:'Traje',dressCopy:'Social completo',details:'Ver detalhes',schedule:'Cronograma',parallax:'Espero você para comemorar!',gallery:'Galeria de fotos',galleryCopy:'Um passeio por momentos inesquecíveis.',gifts:'Lista de presentes',giftCopy:'Sua presença é o nosso maior presente.',photos:'Compartilhe suas fotos',photosCopy:'Envie as fotos para o nosso álbum compartilhado.',social:'Instagram',socialCopy:'Marque usando:',spotify:'Spotify',spotifyCopy:'Qual música não pode faltar?',pass:'Seu convite',passCopy:'Apresente seu QR code na entrada.',rsvp:'Confirmação de presença',deadline:'Confirme sua presença até 1º de novembro.',confirm:'Confirmar presença'}
} as const;

export function SienaInvitation({locale,embedded=false,config,paletteTokens}:Props){
 const root=useRef<HTMLDivElement>(null);const [opened,setOpened]=useState(false);const [opening,setOpening]=useState(false);const [modal,setModal]=useState<string>();const [slide,setSlide]=useState(0);const [sent,setSent]=useState(false);
 const data=useMemo<AuroraConfig>(()=>({...DEFAULT_AURORA_CONFIG,...config,event:{...DEFAULT_AURORA_CONFIG.event,...config?.event},content:{...DEFAULT_AURORA_CONFIG.content,...config?.content},assets:{...DEFAULT_AURORA_CONFIG.assets,...config?.assets},links:{...DEFAULT_AURORA_CONFIG.links,...config?.links},gifts:{...DEFAULT_AURORA_CONFIG.gifts,...config?.gifts},sections:{...DEFAULT_AURORA_CONFIG.sections,...config?.sections},tones:{...DEFAULT_AURORA_CONFIG.tones,...config?.tones},metadata:{...DEFAULT_AURORA_CONFIG.metadata,...config?.metadata},gallery:config?.gallery??DEFAULT_AURORA_CONFIG.gallery,schedule:config?.schedule??DEFAULT_AURORA_CONFIG.schedule}),[config]);
 const t=copy[locale],date=useMemo(()=>new Date(data.event.dateTime),[data.event.dateTime]);const [clock,setClock]=useState([0,0,0,0]);const photos=[2,3,4,5,7,8].map(n=>`${A}foto-0${n}.jpg`);
 useEffect(()=>{const tick=()=>{const d=Math.max(0,date.getTime()-Date.now());setClock([Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60])};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[date]);
 useEffect(()=>{const host=root.current;if(!host)return;const io=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('is-visible',e.isIntersecting)),{root:embedded?host:null,threshold:.12});host.querySelectorAll('.si-reveal').forEach(el=>io.observe(el));return()=>io.disconnect()},[embedded]);
 useEffect(()=>{const id=setInterval(()=>setSlide(v=>(v+1)%photos.length),4200);return()=>clearInterval(id)},[photos.length]);
 const style={'--si-brown':paletteTokens.acentoOscuro,'--si-sand':paletteTokens.acento,'--si-paper':paletteTokens.fondo} as CSSProperties;
 const enabled=(section:keyof AuroraConfig['sections'])=>data.sections[section]!==false;
 const close=()=>setModal(undefined);const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};
 return <div ref={root} className={`siena ${embedded?'si-embedded':''}`} style={style}>
  {!opened&&<div className={`si-envelope ${opening?'is-opening':''}`}><div className="si-envelope-bottom"/><div className="si-envelope-top"/><button onClick={()=>{setOpening(true);window.setTimeout(()=>setOpened(true),1500)}}><img src={`${A}sello-intro-transparente.png`} alt=""/><span>{t.open}</span></button></div>}
  <main>
   <section className="si-hero"><img src={`${A}foto-04.jpg`} alt=""/><div><p>{t.event}</p><h1>{data.event.name}</h1><span>13 • 11 • 2027 · 21:00</span></div><small>{t.scroll} ↓</small></section>
   {enabled('countdown')&&<section className="si-section si-sand si-reveal"><p className="si-eye">{t.less}</p><h2>{t.count}</h2><div className="si-count">{clock.map((n,i)=><div key={t.units[i]}><strong>{String(n).padStart(2,'0')}</strong><span>{t.units[i]}</span></div>)}</div></section>}
   {enabled('location')&&<section className="si-section si-paper si-reveal"><img className="si-icon" src={`${A}icon-map.png`} alt=""/><h2>{t.where}</h2><h3>Salón Eventos Premium</h3><p>Av. Principal 1234, Montevideo<br/>Sábado 13 de noviembre · 21:00</p><div className="si-actions"><button onClick={()=>window.open(data.links.maps,'_blank','noopener')}>{t.map}</button><button>{t.calendar}</button></div></section>}
   {enabled('quote')&&<section className="si-section si-brown si-reveal"><img className="si-icon" src={`${A}icon-corazon.png`} alt=""/><p className="si-quote">{t.quote}</p></section>}
   {enabled('dressCode')&&<Card tone="sand" icon="icon-dress.png" title={t.dress} text={t.dressCopy} button={t.details} onClick={()=>setModal('dress')}/>} 
   {enabled('schedule')&&<section className="si-section si-paper si-reveal"><img className="si-icon" src={`${A}icon-music.png`} alt=""/><h2>{t.schedule}</h2><div className="si-schedule">{[['21:00','Recepción','Bienvenida y primer brindis.'],['22:00','Cena','Una mesa para compartir.'],['00:00','Fiesta','Música y baile.'],['04:00','Cierre','El final de una noche inolvidable.']].map(([time,title,text])=><article key={time}><time>{time}</time><i/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>}
   {enabled('parallax')&&<section className="si-parallax"><img src={`${A}foto-05.jpg`} alt=""/><h2>{t.parallax}</h2></section>}
   {enabled('gallery')&&<section className="si-section si-brown si-gallery si-reveal"><h2>{t.gallery}</h2><p>{t.galleryCopy}</p><div className="si-gallery-stage"><button onClick={()=>setSlide((slide-1+photos.length)%photos.length)}>‹</button><div className="si-gallery-strip">{[-1,0,1].map(offset=>{const index=(slide+offset+photos.length)%photos.length;return <img key={`${slide}-${offset}`} src={photos[index]} alt={`${data.event.name} ${index+1}`}/>})}</div><button onClick={()=>setSlide((slide+1)%photos.length)}>›</button></div><div className="si-dots">{photos.map((_,i)=><button key={i} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`Foto ${i+1}`}/>)}</div></section>}
   {enabled('gifts')&&<Card tone="paper" icon="icon-gift.png" title={t.gifts} text={t.giftCopy} button="Ver cuenta o lista" onClick={()=>setModal('gifts')}/>} 
   {enabled('photoUpload')&&<Card tone="brown" icon="icon-photo.png" title={t.photos} text={t.photosCopy} button="Subir fotos"/>}
   {enabled('social')&&<Card tone="sand" icon="icon-insta.png" title={t.social} text={`${t.socialCopy} #Micaela15Años`} button="Ver Instagram" onClick={()=>setModal('instagram')}/>} 
   {enabled('songSuggestions')&&<Card tone="paper" icon="icon-music.png" title={t.spotify} text={t.spotifyCopy} button="Sugerí música" onClick={()=>setModal('music')}/>} 
   {enabled('qrPass')&&<Card tone="brown" icon="icon-qr.png" title={t.pass} text={t.passCopy} button="Ver mi pase QR" onClick={()=>setModal('qr')}/>} 
   {enabled('rsvp')&&<Card tone="sand" icon="icon-rsvp.png" title={t.rsvp} text={t.deadline} button={t.confirm} onClick={()=>setModal('rsvp')}/>} 
  </main><footer><strong>Save Your Date</strong><p>Invitaciones digitales para momentos inolvidables</p><small>© 2026 Save Your Date · Todos los derechos reservados</small></footer>
  <button className="si-music-float" type="button" aria-label="Música"><span>♪</span></button>
  {modal&&<div className="si-modal" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div><button className="si-close" type="button" onClick={close}>×</button>{modal==='dress'&&<><h2>Dress code</h2><p>Elegante formal. Traje o vestido largo.</p></>}{modal==='gifts'&&<><h2>Mesa de regalos</h2><form className="si-form" onSubmit={e=>{e.preventDefault();close()}}><select defaultValue=""><option value="" disabled>Elegí una opción</option><option>Ver datos bancarios</option><option>Consultar lista de regalos</option></select><input placeholder="Tu nombre (opcional)"/><textarea placeholder="Mensaje para Micaela"/><button>Continuar</button></form></>}{modal==='instagram'&&<><h2>Instagram</h2><p>Compartí tus fotos y etiquetá a <strong>#Micaela15Años</strong>.</p><button type="button" onClick={close}>Entendido</button></>}{modal==='music'&&<><h2>Sugerí una canción</h2><form className="si-form" onSubmit={close}><input required placeholder="Tu nombre"/><input required placeholder="Canción y artista"/><button>Enviar canción</button></form></>}{modal==='qr'&&<><h2>Tu entrada digital</h2><div className="si-qr">QR DEMO</div></>}{modal==='rsvp'&&<>{sent?<><h2>¡Gracias!</h2><p>Tu respuesta fue registrada.</p></>:<><h2>{t.rsvp}</h2><form className="si-form" onSubmit={submit}><input required placeholder="Nombre completo"/><select required defaultValue=""><option value="" disabled>¿Vas a asistir?</option><option>Sí, voy a asistir</option><option>No voy a poder asistir</option></select><select><option>Sin restricciones alimentarias</option><option>Vegetariano/a</option><option>Vegano/a</option><option>Celíaco/a</option></select><textarea placeholder="Mensaje para la anfitriona"/><button>{t.confirm}</button></form></>}</>}</div></div>}
 </div>
}

function Card({tone,icon,title,text,button,onClick}:{tone:'paper'|'sand'|'brown';icon:string;title:string;text:string;button:string;onClick?:()=>void}){return <section className={`si-section si-${tone} si-reveal`}><img className="si-icon" src={`${A}${icon}`} alt=""/><h2>{title}</h2><p>{text}</p><button onClick={onClick}>{button}</button></section>}
