import { useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import { DEFAULT_AURORA_CONFIG, type AuroraConfig, type AuroraLocale, type AuroraPaletteTokens } from '../aurora/config';
import './paper-floral.css';

type Props={locale:AuroraLocale;embedded?:boolean;config?:Partial<AuroraConfig>;paletteTokens:AuroraPaletteTokens;sectionOrder?:string[]};
const A='/desarrollo/boda/invite_006/assets/';
const TEXT={
 es:{hero:'Nos casamos',scroll:'Deslizá para descubrir',less:'Falta cada vez menos',yes:'Para nuestro sí',units:['Días','Horas','Minutos','Segundos'],ceremony:'Ceremonia',celebration:'Celebración',map:'Cómo llegar',quote:'Donde haya amor, allí estaremos',details:'Detalles del gran día',prepared:'Preparamos todo con mucho cariño',dress:'Dress code',dressCopy:'Elegante · Los tonos claros son bienvenidos',gifts:'Regalos',giftCopy:'Tu presencia es nuestro mejor regalo.',message:'Mensaje',messageCopy:'Dejanos un mensaje para conservar de este día.',menu:'Menú',night:'Una noche para celebrar',food:'Podés indicar tus restricciones alimentarias al confirmar.',join:'Te esperamos',rsvp:'Confirmá tu asistencia',deadline:'Por favor, respondé antes del 20 de febrero de 2027.',send:'Enviar confirmación',thanks:'¡Asistencia confirmada! Gracias.',closing:'Gracias por ser parte',closingCopy:'Estamos felices de compartir este momento con ustedes.'},
 en:{hero:'We are getting married',scroll:'Scroll to discover',less:'The wait is getting shorter',yes:'Until we say I do',units:['Days','Hours','Minutes','Seconds'],ceremony:'Ceremony',celebration:'Celebration',map:'Get directions',quote:'Where there is love, there we will be',details:'Details of our day',prepared:'Everything prepared with love',dress:'Dress code',dressCopy:'Formal attire · Light colors are welcome',gifts:'Gifts',giftCopy:'Your presence is our greatest gift.',message:'Message',messageCopy:'Leave us a message to remember this day.',menu:'Menu',night:'A night to celebrate',food:'Please share dietary restrictions when confirming.',join:'We hope you can join us',rsvp:'Confirm your attendance',deadline:'Please reply by February 20, 2027.',send:'Send confirmation',thanks:'Attendance confirmed. Thank you!',closing:'Thank you for being part',closingCopy:'We cannot wait to share this moment with you.'},
 pt:{hero:'Vamos nos casar',scroll:'Deslize para descobrir',less:'Falta cada vez menos',yes:'Para o nosso sim',units:['Dias','Horas','Minutos','Segundos'],ceremony:'Cerimônia',celebration:'Celebração',map:'Como chegar',quote:'Onde houver amor, ali estaremos',details:'Detalhes do grande dia',prepared:'Preparamos tudo com carinho',dress:'Dress code',dressCopy:'Traje social completo · Tons claros são bem-vindos',gifts:'Presentes',giftCopy:'Sua presença é o nosso maior presente.',message:'Recado',messageCopy:'Deixe uma mensagem para guardarmos deste dia.',menu:'Menu',night:'Uma noite para celebrar',food:'Restrições alimentares podem ser informadas na confirmação.',join:'Esperamos por você',rsvp:'Confirme sua presença',deadline:'Por favor, responda até 20 de fevereiro de 2027.',send:'Enviar confirmação',thanks:'Presença confirmada. Obrigado!',closing:'Obrigado por fazer parte',closingCopy:'Mal podemos esperar para viver este momento com vocês.'}
} as const;

export function PaperFloralInvitation({locale,embedded=false,config,paletteTokens}:Props){
 const rootRef=useRef<HTMLDivElement>(null);const musicRef=useRef<{context:AudioContext;nodes:OscillatorNode[]} | null>(null);const [sent,setSent]=useState(false);const [gift,setGift]=useState(false);const [message,setMessage]=useState(false);const [messageSent,setMessageSent]=useState(false);const [musicPlaying,setMusicPlaying]=useState(false);
 const data=useMemo<AuroraConfig>(()=>({...DEFAULT_AURORA_CONFIG,...config,event:{...DEFAULT_AURORA_CONFIG.event,...config?.event},content:{...DEFAULT_AURORA_CONFIG.content,...config?.content},assets:{...DEFAULT_AURORA_CONFIG.assets,...config?.assets},links:{...DEFAULT_AURORA_CONFIG.links,...config?.links},gifts:{...DEFAULT_AURORA_CONFIG.gifts,...config?.gifts},sections:{...DEFAULT_AURORA_CONFIG.sections,...config?.sections},tones:{...DEFAULT_AURORA_CONFIG.tones,...config?.tones},metadata:{...DEFAULT_AURORA_CONFIG.metadata,...config?.metadata},gallery:config?.gallery??DEFAULT_AURORA_CONFIG.gallery,schedule:config?.schedule??DEFAULT_AURORA_CONFIG.schedule}),[config]);
 const t=TEXT[locale],date=useMemo(()=>new Date(data.event.dateTime),[data.event.dateTime]);const [clock,setClock]=useState([0,0,0,0]);const names=data.event.name.split(/\s*&\s*/);
 useEffect(()=>{const tick=()=>{const g=Math.max(0,date.getTime()-Date.now());setClock([Math.floor(g/86400000),Math.floor(g/3600000)%24,Math.floor(g/60000)%60,Math.floor(g/1000)%60])};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[date]);
 useEffect(()=>{const root=rootRef.current;if(!root)return;const observer=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('is-visible',e.isIntersecting)),{threshold:.08});root.querySelectorAll('.pf-section').forEach(x=>observer.observe(x));return()=>observer.disconnect()},[]);
 useEffect(()=>{const root=rootRef.current,photo=root?.querySelector<HTMLElement>('.pf-parallax img'),section=root?.querySelector<HTMLElement>('.pf-parallax'),music=root?.querySelector<HTMLElement>('.pf-music');if(!root||!photo||!section)return;let f=0;const move=()=>{cancelAnimationFrame(f);f=requestAnimationFrame(()=>{const rr=root.getBoundingClientRect(),r=section.getBoundingClientRect(),p=(r.top+r.height/2-(rr.top+rr.height/2))/(rr.height+r.height);photo.style.setProperty('--pf-y',`${Math.max(-90,Math.min(90,p*-190))}px`);if(embedded&&music){music.style.setProperty('--pf-music-top',`${root.scrollTop+root.clientHeight-66}px`);root.style.setProperty('--pf-scroll-y',`${root.scrollTop}px`)}})};move();const resizeObserver=new ResizeObserver(move);resizeObserver.observe(root);root.addEventListener('scroll',move,{passive:true});return()=>{cancelAnimationFrame(f);resizeObserver.disconnect();root.removeEventListener('scroll',move)}},[embedded]);
 useEffect(()=>()=>{musicRef.current?.nodes.forEach(node=>node.stop());void musicRef.current?.context.close()},[]);
 const style={'--pf-blue':paletteTokens.acento,'--pf-dark':paletteTokens.acentoOscuro,'--pf-ice':paletteTokens.alterno} as CSSProperties;
 const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};
 const submitMessage=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const payload={kind:'guest-message',...Object.fromEntries(new FormData(e.currentTarget))};try{if(data.links.rsvpEndpoint){const response=await fetch(data.links.rsvpEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('message failed')}setMessageSent(true)}catch{setMessageSent(false)}};
 const toggleMusic=()=>{if(musicRef.current){musicRef.current.nodes.forEach(node=>node.stop());void musicRef.current.context.close();musicRef.current=null;setMusicPlaying(false);return}const context=new AudioContext();const gain=context.createGain();gain.gain.value=.018;gain.connect(context.destination);const nodes=[261.63,329.63,392].map((frequency,index)=>{const oscillator=context.createOscillator();oscillator.type='sine';oscillator.frequency.value=frequency/2;const voice=context.createGain();voice.gain.value=.42-index*.08;oscillator.connect(voice).connect(gain);oscillator.start();return oscillator});musicRef.current={context,nodes};setMusicPlaying(true)};
 return <div ref={rootRef} className={`paper-floral ${embedded?'pf-embedded':''}`} style={style}><main className="pf-main">
  <section className="pf-section pf-hero"><img className="pf-corner" src={`${A}floral-corner.webp`} alt=""/><div className="pf-content"><p className="pf-eye">{t.hero}</p><h1>{names.map((n,i)=><span key={n}>{i>0&&<i>&amp;</i>}{n}</span>)}</h1><p className="pf-date">20 · 03 · 2027</p><p className="pf-place">São Paulo</p></div><span className="pf-scroll">{t.scroll} ↓</span></section>
  <section className="pf-section pf-blue"><img className="pf-orn pf-right" src={`${A}floral-side.webp`} alt=""/><div className="pf-content"><img className="pf-icon" src={`${A}icon-rings.webp`} alt=""/><p className="pf-eye">{t.less}</p><h2>{t.yes}</h2><div className="pf-count">{clock.map((v,i)=><div key={t.units[i]}><strong>{String(v).padStart(2,'0')}</strong><span>{t.units[i]}</span></div>)}</div></div></section>
  <section className="pf-section pf-tint"><img className="pf-orn pf-left" src={`${A}floral-side.webp`} alt=""/><div className="pf-events"><article><img className="pf-icon" src={`${A}icon-church.webp`} alt=""/><p className="pf-eye">{t.ceremony}</p><h3>Iglesia Nossa Senhora<br/>do Brasil</h3><p>Praça Nossa Senhora do Brasil<br/>Jardim América · 17 h</p><button className="pf-btn" onClick={()=>window.open(data.links.maps,'_blank','noopener')}>{t.map}</button></article><article><img className="pf-icon" src={`${A}icon-cake.webp`} alt=""/><p className="pf-eye">{t.celebration}</p><h3>Casa Petra</h3><p>Av. Aratãs, 1010 · Moema<br/>Desde las 19:30 h</p><button className="pf-btn" onClick={()=>window.open(data.links.maps,'_blank','noopener')}>{t.map}</button></article></div></section>
  <section className="pf-section pf-parallax"><img src={`${A}couple.webp`} alt={data.event.name}/><p>{t.quote}</p></section>
  <section className="pf-section"><img className="pf-orn pf-right" src={`${A}floral-side.webp`} alt=""/><div className="pf-content"><p className="pf-eye">{t.details}</p><h2>{t.prepared}</h2><div className="pf-details"><article><img className="pf-icon" src={`${A}icon-camera.webp`} alt=""/><h3>{t.dress}</h3><p>{t.dressCopy}</p></article><article><img className="pf-icon" src={`${A}icon-gift.webp`} alt=""/><h3>{t.gifts}</h3><p>{t.giftCopy}</p><button className="pf-btn" onClick={()=>setGift(true)}>Ver opciones</button></article><article><img className="pf-icon" src={`${A}icon-envelope.webp`} alt=""/><h3>{t.message}</h3><p>{t.messageCopy}</p><button className="pf-btn" onClick={()=>{setMessage(true);setMessageSent(false)}}>Escribir</button></article></div></div></section>
  <section className="pf-section pf-blue"><img className="pf-orn pf-left" src={`${A}floral-side.webp`} alt=""/><div className="pf-content"><img className="pf-icon" src={`${A}icon-cake.webp`} alt=""/><p className="pf-eye">{t.menu}</p><h2>{t.night}</h2><div className="pf-menu"><p><strong>Bienvenida</strong><span>Canapés artesanales y espumante</span></p><p><strong>Cena</strong><span>Sabores contemporáneos con ingredientes brasileños</span></p><p><strong>Dulces y torta</strong><span>Selección especial para brindar por el amor</span></p></div><p className="pf-copy">{t.food}</p></div></section>
  <section className="pf-section pf-tint"><img className="pf-orn pf-right" src={`${A}floral-side.webp`} alt=""/><div className="pf-content"><img className="pf-icon" src={`${A}icon-envelope.webp`} alt=""/><p className="pf-eye">{t.join}</p><h2>{t.rsvp}</h2><p className="pf-copy">{t.deadline}</p>{sent?<p className="pf-thanks">{t.thanks}</p>:<form className="pf-form" onSubmit={submit}><input required placeholder="Nombre y apellido"/><select required defaultValue=""><option value="" disabled>¿Vas a asistir?</option><option>Sí, confirmo mi asistencia</option><option>No podré asistir</option></select><select><option>Sin restricciones alimentarias</option><option>Vegetariano/a</option><option>Vegano/a</option><option>Celíaco/a · sin gluten</option></select><textarea rows={3} placeholder="Mensaje para los novios (opcional)"/><button className="pf-btn">{t.send}</button></form>}</div></section>
  <section className="pf-section pf-closing"><img className="pf-orn pf-left" src={`${A}floral-side.webp`} alt=""/><div className="pf-content"><p className="pf-eye">{t.closing}</p><h2>{names.map((n,i)=><span key={n}>{i>0&&<i>&amp;</i>}{n}</span>)}</h2><p className="pf-copy">{t.closingCopy}</p></div></section>
 </main><footer className="pf-footer"><strong>Save Your Date</strong><p>Invitaciones digitales para momentos inolvidables · © 2026</p></footer><button className={`pf-music ${musicPlaying?'is-playing':''}`} aria-label={musicPlaying?'Pausar música':'Reproducir música'} aria-pressed={musicPlaying} onClick={toggleMusic}>♫</button>{gift&&<div className="pf-modal"><div><button onClick={()=>setGift(false)}>×</button><h2>{t.gifts}</h2><p>PIX: marina.rafael@exemplo.com</p></div></div>}{message&&<div className="pf-modal"><div className="pf-message-modal"><button onClick={()=>setMessage(false)}>×</button><h2>{t.message}</h2>{messageSent?<><p>Tu mensaje fue enviado y aparecerá entre los mensajes recibidos.</p><button className="pf-btn" onClick={()=>setMessage(false)}>Cerrar</button></>:<form className="pf-form" onSubmit={submitMessage}><input name="name" required placeholder="Nombre y apellido"/><textarea name="message" required rows={5} placeholder="Escribí tu mensaje"/><button className="pf-btn">Enviar mensaje</button></form>}</div></div>}</div>
}
